name: Release npm package

on:
  push:
    tags:
    - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  pkg:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '25.x'
        registry-url: https://registry.npmjs.org/
        scope: '@appthreat'
    - name: Release npm package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        npm install
        npm publish --provenance --access=public
